### ISSUE TITLE
报道

### ISSUE THREAD

**Issue by dark-flame-master** [jnrain/helloworld#17]
有谁能告诉我怎么换头像吗？
那个gravatar怎么都打不开。

**Comment by xen0n** [comment]
啊哈... 你需要科学上网... 学校里的话电信确实是偶尔上不去的, 移动和联通的帐号我没有, 教育网(流量号)应该是可以上的

**Comment by xen0n** [comment]
成员已添加, 欢迎加入技术公社大家庭~ closing
