### ISSUE TITLE
 img bug

### ISSUE THREAD

**Issue by yuwei845433424** [jnrain/helloworld#21]
那个写以物换物的前端的时候，出现有了一个bug显示的是SyntaxError: syntax errordiv class="comic"><img src="${imgSrc}"

**Comment by xen0n** [comment]
请把bug提交到相关的版本库，这里不适合。closing

**Comment by ryanaltair** [comment]
什么bug? 请教下 @xeon ，在isuue tracker 那里提问然后@ 他吧

发自我的 Windows Phone
